uploads = []
generated = []

[[outputs]]
id = "21bRfyoZxcRZK8Bxi8L5p"
uri = "file://README.md"
type = "text"
title = "README.md — Yolobit IoT Dashboard"

[[outputs]]
id = "Qw_DjLGhvX4aLUe42-h6Z"
uri = "file://readmever2.md"
type = "text"
title = "readmever2.md — MQTT Architecture"
